# Generated by Django 3.1.7 on 2021-04-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguage', '0007_auto_20210402_0613'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(related_name='user_interests', to='programmingLanguage.Language'),
        ),
    ]
