# Generated by Django 3.1.7 on 2021-04-16 23:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210402_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='star_count',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='profile',
            name='stars',
            field=models.ManyToManyField(blank=True, default=None, related_name='star', to=settings.AUTH_USER_MODEL),
        ),
    ]
