# Generated by Django 3.1.7 on 2021-07-11 03:21

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210711_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatar.png', upload_to=account.models.user_directory_path),
        ),
    ]
