# Generated by Django 3.1.7 on 2021-04-01 06:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datastructure',
            old_name='datail',
            new_name='detail',
        ),
        migrations.AddField(
            model_name='language',
            name='detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
