# Generated by Django 3.1.7 on 2021-04-01 07:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguage', '0002_auto_20210401_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastructure',
            name='detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
