# Generated by Django 3.1.7 on 2021-04-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguage', '0004_category_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.SlugField(max_length=10, unique=True),
        ),
    ]
